const express = require('express')
require('./database/db')
const router = require('./Routers/route')
const app = express()
app.use(express.json())
app.use(router)
app.listen(3002 , () => console.log("Server is Running on port Number : 3002"))
